package com.hjm.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Bill_Sep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_sep.id
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_sep.clientid
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private Integer clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_sep.billid
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_sep.updatetime
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_sep.id
     *
     * @return the value of bill_sep.id
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_sep.id
     *
     * @param id the value for bill_sep.id
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_sep.clientid
     *
     * @return the value of bill_sep.clientid
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public Integer getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_sep.clientid
     *
     * @param clientid the value for bill_sep.clientid
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setClientid(Integer clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_sep.billid
     *
     * @return the value of bill_sep.billid
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_sep.billid
     *
     * @param billid the value for bill_sep.billid
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_sep.updatetime
     *
     * @return the value of bill_sep.updatetime
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_sep.updatetime
     *
     * @param updatetime the value for bill_sep.updatetime
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    @Override
    public String toString() {
        return "Bill_Sep{" +
                "id=" + id +
                ", clientid=" + clientid +
                ", billid=" + billid +
                ", updatetime=" + updatetime +
                '}';
    }
}