package com.hjm.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.id
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.product_img
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private String productImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.contact_img
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private String contactImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.starttime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.updatetime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.endtime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.leaderid
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private Integer leaderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.product
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private String product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.shop
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private String shop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.status
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.target
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.address
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.id
     *
     * @return the value of bill.id
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.id
     *
     * @param id the value for bill.id
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.product_img
     *
     * @return the value of bill.product_img
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.product_img
     *
     * @param productImg the value for bill.product_img
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.contact_img
     *
     * @return the value of bill.contact_img
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public String getContactImg() {
        return contactImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.contact_img
     *
     * @param contactImg the value for bill.contact_img
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setContactImg(String contactImg) {
        this.contactImg = contactImg == null ? null : contactImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.starttime
     *
     * @return the value of bill.starttime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.starttime
     *
     * @param starttime the value for bill.starttime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.updatetime
     *
     * @return the value of bill.updatetime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.updatetime
     *
     * @param updatetime the value for bill.updatetime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.endtime
     *
     * @return the value of bill.endtime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.endtime
     *
     * @param endtime the value for bill.endtime
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.leaderid
     *
     * @return the value of bill.leaderid
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public Integer getLeaderid() {
        return leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.leaderid
     *
     * @param leaderid the value for bill.leaderid
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setLeaderid(Integer leaderid) {
        this.leaderid = leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.product
     *
     * @return the value of bill.product
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public String getProduct() {
        return product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.product
     *
     * @param product the value for bill.product
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setProduct(String product) {
        this.product = product == null ? null : product.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.shop
     *
     * @return the value of bill.shop
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public String getShop() {
        return shop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.shop
     *
     * @param shop the value for bill.shop
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setShop(String shop) {
        this.shop = shop == null ? null : shop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.status
     *
     * @return the value of bill.status
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.status
     *
     * @param status the value for bill.status
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.target
     *
     * @return the value of bill.target
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.target
     *
     * @param target the value for bill.target
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.address
     *
     * @return the value of bill.address
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.address
     *
     * @param address the value for bill.address
     *
     * @mbggenerated Mon Sep 02 19:12:28 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Override
    public String toString() {
        return "Bill{" +
                "id=" + id +
                ", productImg='" + productImg + '\'' +
                ", contactImg='" + contactImg + '\'' +
                ", starttime=" + starttime +
                ", updatetime=" + updatetime +
                ", endtime=" + endtime +
                ", leaderid=" + leaderid +
                ", product='" + product + '\'' +
                ", shop='" + shop + '\'' +
                ", status=" + status +
                ", target='" + target + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}