package com.hjm.pojo;

public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.id
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.rights
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private String rights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.password
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.age
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.tel
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.username
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.sex
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.address
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.id
     *
     * @return the value of client.id
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.id
     *
     * @param id the value for client.id
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.rights
     *
     * @return the value of client.rights
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.rights
     *
     * @param rights the value for client.rights
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setRights(String rights) {
        this.rights = rights == null ? null : rights.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.password
     *
     * @return the value of client.password
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.password
     *
     * @param password the value for client.password
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.age
     *
     * @return the value of client.age
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.age
     *
     * @param age the value for client.age
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.tel
     *
     * @return the value of client.tel
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.tel
     *
     * @param tel the value for client.tel
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.username
     *
     * @return the value of client.username
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.username
     *
     * @param username the value for client.username
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.sex
     *
     * @return the value of client.sex
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.sex
     *
     * @param sex the value for client.sex
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.address
     *
     * @return the value of client.address
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.address
     *
     * @param address the value for client.address
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Override
    public String toString() {
        return "Client{" +
                "id=" + id +
                ", rights='" + rights + '\'' +
                ", password='" + password + '\'' +
                ", age=" + age +
                ", tel='" + tel + '\'' +
                ", username='" + username + '\'' +
                ", sex='" + sex + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}