package com.hjm.dao;

import com.hjm.pojo.Bill_Sep;
import com.hjm.pojo.Bill_SepExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Bill_SepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int countByExample(Bill_SepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int deleteByExample(Bill_SepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int insert(Bill_Sep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int insertSelective(Bill_Sep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    List<Bill_Sep> selectByExample(Bill_SepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    Bill_Sep selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bill_Sep record, @Param("example") Bill_SepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int updateByExample(@Param("record") Bill_Sep record, @Param("example") Bill_SepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int updateByPrimaryKeySelective(Bill_Sep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_sep
     *
     * @mbggenerated Mon Sep 02 18:51:26 CST 2019
     */
    int updateByPrimaryKey(Bill_Sep record);

}